module.exports = {
  'About': 'about',
  'The Crime Victim Assistance Program (CVAP)': 'a',
  'Family Justice Centers': 'b',
  'Program for Survivors of Torture': false,
  'Mission: VetCheck': 'k',
  'The Trevor Project': 'e',
  'LGBT National Help Center': 'l',
  'Mobile Treatment Services Accessible Through the Single Point of Access': 'n',
  'Mobile Crisis Teams': 'm',
  'Friendly Visiting and Friendly VOICES': 'g',
  'Geriatric Mental Health Initiative': 'c',
  'NYC Well': 'x',
  'NYC Care': 'p',
  'NYC Family Resource Centers': 'b',
  'Early Childhood Mental Health Network': 'q',
  'Comprehensive Psychiatric Emergency Services Program (CPEP) at Health + Hospitals': 'r',
  'Clubhouses': false,
  'School Mental Health Services': 's',
  'Family Counseling': 'h',
  'Drop-in Centers for Runaway and Homeless Youth': 'i',
  'Syringe Service Programs': false,
  'Naloxone': 't',
  'Gotham Pride Health Centers': false,
  '3-2-1 Impact': 'v',
  'Mental Health Integrated in Primary Care': 'w',
  'Child Use of Prescription Pain Relievers or Heroin': 'u',
  'COVID-19 Community Conversations': 'y',
  'Clubhouses': 'z'
};