module.exports = {
  'The Crime Victim Assistance Program (CVAP)': 'a',
  'Family Justice Centers': 'b',
  'Program for Survivors of Torture': false,
  'Mission: VetCheck': 'k',
  'The Trevor Project': 'e',
  'LGBT National Help Center': 'l',
  'Mobile Treatment Services Accessible Through the Single Point of Access': 'n',
  'Mobile Crisis Teams': 'm',
  'Friendly Visiting and Friendly VOICES': 'g',
  'Geriatric Mental Health Initiative': 'c',
  'NYC Well': 'o',
  'NYC Care': 'f',
  'NYC Family Resource Centers': 'b',
  'Early Childhood Mental Health Network': 'h',
  'Comprehensive Psychiatric Emergency Services Program (CPEP)':'f',
  'Clubhouses': 'd',
  'School Mental Health Services': 'b',
  'Family Counseling': 'h',
  'Assisted Outpatient Treatment (AOT)': 'f',
  'Drop-in Centers for Runaway and Homeless Youth': 'i',
  'Syringe Service Programs': 'j',
  'Naloxone': 'f',
  'Gotham Pride Health Centers': false,
  '3-2-1 Impact': 'f',
  'Mental Health Integrated in Primary Care': 'f',
  'Intensive Mobile Treatment': 'f'
};